CREATE TABLE PM25_1g_cons
SELECT `Kod stacji` AS Measure_Date, 'ZpSzczecin002' AS Station_Code, `ZpSzczecin002` AS Pollution_Level FROM `2006_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpBydgWarszawska' AS Station_Code, `KpBydgWarszawska` AS Pollution_Level FROM `2007_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczecin002' AS Station_Code, `ZpSzczecin002` AS Pollution_Level FROM `2007_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpBydgWarszawska' AS Station_Code, `KpBydgWarszawska` AS Pollution_Level FROM `2008_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBulw6118' AS Station_Code, `MpKrakowWIOSBulw6118` AS Pollution_Level FROM `2008_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSPrad6115' AS Station_Code, `MpKrakowWIOSPrad6115` AS Pollution_Level FROM `2008_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkJasloWIOSFabr' AS Station_Code, `PkJasloWIOSFabr` AS Pollution_Level FROM `2008_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkPrzemyslWIOSMick' AS Station_Code, `PkPrzemyslWIOSMick` AS Pollution_Level FROM `2008_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.a09a' AS Station_Code, `Pm.a09a` AS Pollution_Level FROM `2008_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpWKP001' AS Station_Code, `WpWKP001` AS Pollution_Level FROM `2008_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczecin002' AS Station_Code, `ZpSzczecin002` AS Pollution_Level FROM `2008_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWrocKorzA' AS Station_Code, `DsWrocKorzA` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpBydgWarszawska' AS Station_Code, `KpBydgWarszawska` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzWIOSACzernik' AS Station_Code, `LdLodzWIOSACzernik` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdZgierzWIOSAMielcza' AS Station_Code, `LdZgierzWIOSAMielcza` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuZgoraWIOS_AUT' AS Station_Code, `LuZgoraWIOS_AUT` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSAKra6117' AS Station_Code, `MpKrakowWIOSAKra6117` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBulw6118' AS Station_Code, `MpKrakowWIOSBulw6118` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSPrad6115' AS Station_Code, `MpKrakowWIOSPrad6115` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarszUrsynow' AS Station_Code, `MzWarszUrsynow` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'OpKkozle1a' AS Station_Code, `OpKkozle1a` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdBialyMiejska' AS Station_Code, `PdBialyMiejska` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkJasloWIOSFabr' AS Station_Code, `PkJasloWIOSFabr` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkPrzemyslWIOSMick' AS Station_Code, `PkPrzemyslWIOSMick` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkRzeszWIOSSzop' AS Station_Code, `PkRzeszWIOSSzop` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlGliwiGliw_mewy' AS Station_Code, `SlGliwiGliw_mewy` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlKatowKato_kossu' AS Station_Code, `SlKatowKato_kossu` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZabrzZabr_sklod' AS Station_Code, `SlZabrzZabr_sklod` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmOlsztyWIOS_Puszkin' AS Station_Code, `WmOlsztyWIOS_Puszkin` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpWKP001' AS Station_Code, `WpWKP001` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpWKPKalisz007/10' AS Station_Code, `WpWKPKalisz007/10` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczecin001' AS Station_Code, `ZpSzczecin001` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczecin002' AS Station_Code, `ZpSzczecin002` AS Pollution_Level FROM `2009_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWrocKorzA' AS Station_Code, `DsWrocKorzA` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpBydgWarszawska' AS Station_Code, `KpBydgWarszawska` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpTorunDziewulsk' AS Station_Code, `KpTorunDziewulsk` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzWIOSACzernik' AS Station_Code, `LdLodzWIOSACzernik` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdZgierzWIOSAMielcza' AS Station_Code, `LdZgierzWIOSAMielcza` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuZgoraWIOS_AUT' AS Station_Code, `LuZgoraWIOS_AUT` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSAKra6117' AS Station_Code, `MpKrakowWIOSAKra6117` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBuja6119' AS Station_Code, `MpKrakowWIOSBuja6119` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBulw6118' AS Station_Code, `MpKrakowWIOSBulw6118` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSPrad6115' AS Station_Code, `MpKrakowWIOSPrad6115` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'OpKkozle1a' AS Station_Code, `OpKkozle1a` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdBialyMiejska' AS Station_Code, `PdBialyMiejska` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkJasloWIOSSikorskiego' AS Station_Code, `PkJasloWIOSSikorskiego` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkPrzemyslWIOSMick' AS Station_Code, `PkPrzemyslWIOSMick` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkRzeszWIOSSzop' AS Station_Code, `PkRzeszWIOSSzop` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.a08a' AS Station_Code, `Pm.a08a` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkKielJagielWios' AS Station_Code, `SkKielJagielWios` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlGliwiGliw_mewy' AS Station_Code, `SlGliwiGliw_mewy` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlKatowKato_kossu' AS Station_Code, `SlKatowKato_kossu` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmOlsztyWIOS_Puszkin' AS Station_Code, `WmOlsztyWIOS_Puszkin` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpWKP001' AS Station_Code, `WpWKP001` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpWKPKalisz007/10' AS Station_Code, `WpWKPKalisz007/10` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczecin001' AS Station_Code, `ZpSzczecin001` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczecin002' AS Station_Code, `ZpSzczecin002` AS Pollution_Level FROM `2010_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWrocWisA' AS Station_Code, `DsWrocWisA` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpBydgWarszawska' AS Station_Code, `KpBydgWarszawska` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpTorunDziewulsk' AS Station_Code, `KpTorunDziewulsk` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzWIOSACzernik' AS Station_Code, `LdLodzWIOSACzernik` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdZgierzWIOSAMielcza' AS Station_Code, `LdZgierzWIOSAMielcza` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuZgoraWIOS_AUT' AS Station_Code, `LuZgoraWIOS_AUT` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSAKra6117' AS Station_Code, `MpKrakowWIOSAKra6117` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBuja6119' AS Station_Code, `MpKrakowWIOSBuja6119` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBulw6118' AS Station_Code, `MpKrakowWIOSBulw6118` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarNiepodKom' AS Station_Code, `MzWarNiepodKom` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarszUrsynow' AS Station_Code, `MzWarszUrsynow` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'OpKkozle1a' AS Station_Code, `OpKkozle1a` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdBialyMiejska' AS Station_Code, `PdBialyMiejska` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkJasloWIOSSikorskiego' AS Station_Code, `PkJasloWIOSSikorskiego` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkPrzemyslWIOSMick' AS Station_Code, `PkPrzemyslWIOSMick` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkRzeszWIOSSzop' AS Station_Code, `PkRzeszWIOSSzop` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.a08a' AS Station_Code, `Pm.a08a` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkKielJagielWios' AS Station_Code, `SkKielJagielWios` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlGliwiGliw_mewy' AS Station_Code, `SlGliwiGliw_mewy` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlKatowKato_kossu' AS Station_Code, `SlKatowKato_kossu` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmOlsztyWIOS_Puszkin' AS Station_Code, `WmOlsztyWIOS_Puszkin` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpWKP001' AS Station_Code, `WpWKP001` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpWKPKalisz007/10' AS Station_Code, `WpWKPKalisz007/10` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczecin001' AS Station_Code, `ZpSzczecin001` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczecin002' AS Station_Code, `ZpSzczecin002` AS Pollution_Level FROM `2011_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWrocWisA' AS Station_Code, `DsWrocWisA` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpAirpWiktorowo' AS Station_Code, `KpAirpWiktorowo` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpBydgPlPozn' AS Station_Code, `KpBydgPlPozn` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpBydgWarszawska' AS Station_Code, `KpBydgWarszawska` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpTorunDziewulsk' AS Station_Code, `KpTorunDziewulsk` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzWIOSACzernik' AS Station_Code, `LdLodzWIOSACzernik` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdZgierzWIOSAMielcza' AS Station_Code, `LdZgierzWIOSAMielcza` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuZgoraWIOS_AUT' AS Station_Code, `LuZgoraWIOS_AUT` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSAKra6117' AS Station_Code, `MpKrakowWIOSAKra6117` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBuja6119' AS Station_Code, `MpKrakowWIOSBuja6119` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBulw6118' AS Station_Code, `MpKrakowWIOSBulw6118` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzSiedlceKonar' AS Station_Code, `MzSiedlceKonar` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarNiepodKom' AS Station_Code, `MzWarNiepodKom` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarszUrsynow' AS Station_Code, `MzWarszUrsynow` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'OpKkozle1a' AS Station_Code, `OpKkozle1a` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdBialyMiejska' AS Station_Code, `PdBialyMiejska` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkJasloWIOSSikorskiego' AS Station_Code, `PkJasloWIOSSikorskiego` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkPrzemyslWIOSMick' AS Station_Code, `PkPrzemyslWIOSMick` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkRzeszWIOSSzop' AS Station_Code, `PkRzeszWIOSSzop` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.a08a' AS Station_Code, `Pm.a08a` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.AM12.a' AS Station_Code, `Pm.AM12.a` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkKielJagielWios' AS Station_Code, `SkKielJagielWios` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkPolanRuszcz' AS Station_Code, `SkPolanRuszcz` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlGliwiGliw_mewy' AS Station_Code, `SlGliwiGliw_mewy` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlKatowKato_kossu' AS Station_Code, `SlKatowKato_kossu` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpWKP001' AS Station_Code, `WpWKP001` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpWKPKalisz007/10' AS Station_Code, `WpWKPKalisz007/10` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczecin001' AS Station_Code, `ZpSzczecin001` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczecin002' AS Station_Code, `ZpSzczecin002` AS Pollution_Level FROM `2012_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWrocWisA' AS Station_Code, `DsWrocWisA` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpAirpWiktorowo' AS Station_Code, `KpAirpWiktorowo` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpBydgWarszawska' AS Station_Code, `KpBydgWarszawska` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdZgierzWIOSAMielcza' AS Station_Code, `LdZgierzWIOSAMielcza` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuZgoraWIOS_AUT' AS Station_Code, `LuZgoraWIOS_AUT` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSAKra6117' AS Station_Code, `MpKrakowWIOSAKra6117` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBuja6119' AS Station_Code, `MpKrakowWIOSBuja6119` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBulw6118' AS Station_Code, `MpKrakowWIOSBulw6118` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzSiedlceKonar' AS Station_Code, `MzSiedlceKonar` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarNiepodKom' AS Station_Code, `MzWarNiepodKom` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarszUrsynow' AS Station_Code, `MzWarszUrsynow` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'OpKkozle1a' AS Station_Code, `OpKkozle1a` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdBialyMiejska' AS Station_Code, `PdBialyMiejska` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkPrzemyslWIOSGrunw' AS Station_Code, `PkPrzemyslWIOSGrunw` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.a08a' AS Station_Code, `Pm.a08a` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkMalogCemen3' AS Station_Code, `SkMalogCemen3` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkPolanRuszcz' AS Station_Code, `SkPolanRuszcz` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlGliwiGliw_mewy' AS Station_Code, `SlGliwiGliw_mewy` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlKatowKato_kossu' AS Station_Code, `SlKatowKato_kossu` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZlotyJano_lesni' AS Station_Code, `SlZlotyJano_lesni` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpWKP001' AS Station_Code, `WpWKP001` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpWKPKalisz007/10' AS Station_Code, `WpWKPKalisz007/10` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczecin002' AS Station_Code, `ZpSzczecin002` AS Pollution_Level FROM `2013_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWrocWisA' AS Station_Code, `DsWrocWisA` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpAirpWiktorowo' AS Station_Code, `KpAirpWiktorowo` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpBydgPlPozn' AS Station_Code, `KpBydgPlPozn` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpBydgWarszawska' AS Station_Code, `KpBydgWarszawska` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpTorunDziewulsk' AS Station_Code, `KpTorunDziewulsk` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzWIOSACzernik' AS Station_Code, `LdLodzWIOSACzernik` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdZgierzWIOSAMielcza' AS Station_Code, `LdZgierzWIOSAMielcza` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuZgoraWIOS_AUT' AS Station_Code, `LuZgoraWIOS_AUT` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSAKra6117' AS Station_Code, `MpKrakowWIOSAKra6117` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBuja6119' AS Station_Code, `MpKrakowWIOSBuja6119` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBulw6118' AS Station_Code, `MpKrakowWIOSBulw6118` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzLegionZegIMGW' AS Station_Code, `MzLegionZegIMGW` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzPlockReja' AS Station_Code, `MzPlockReja` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzRadomTochter' AS Station_Code, `MzRadomTochter` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzSiedlceKonar' AS Station_Code, `MzSiedlceKonar` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarNiepodKom' AS Station_Code, `MzWarNiepodKom` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarszUrsynow' AS Station_Code, `MzWarszUrsynow` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzZyrardRoosevel' AS Station_Code, `MzZyrardRoosevel` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'OpKkozle1a' AS Station_Code, `OpKkozle1a` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdBialyMiejska' AS Station_Code, `PdBialyMiejska` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdSuwPulaski' AS Station_Code, `PdSuwPulaski` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkPrzemyslWIOSGrunw' AS Station_Code, `PkPrzemyslWIOSGrunw` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.a08a' AS Station_Code, `Pm.a08a` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.AM12.a' AS Station_Code, `Pm.AM12.a` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkKielJagielWios' AS Station_Code, `SkKielJagielWios` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkMalogCemen3' AS Station_Code, `SkMalogCemen3` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkPolanRuszcz' AS Station_Code, `SkPolanRuszcz` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlGliwiGliw_mewy' AS Station_Code, `SlGliwiGliw_mewy` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlKatowKato_kossu' AS Station_Code, `SlKatowKato_kossu` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZlotyJano_lesni' AS Station_Code, `SlZlotyJano_lesni` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmOlsztyWIOS_Puszkin' AS Station_Code, `WmOlsztyWIOS_Puszkin` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpWKP001' AS Station_Code, `WpWKP001` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpWKPKalisz007/10' AS Station_Code, `WpWKPKalisz007/10` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczecin001' AS Station_Code, `ZpSzczecin001` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczecin002' AS Station_Code, `ZpSzczecin002` AS Pollution_Level FROM `2014_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsJelGorOgin' AS Station_Code, `DsJelGorOgin` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWrocAlWisn' AS Station_Code, `DsWrocAlWisn` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWrocWybCon' AS Station_Code, `DsWrocWybCon` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpBydPlPozna' AS Station_Code, `KpBydPlPozna` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpBydWarszaw' AS Station_Code, `KpBydWarszaw` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpToruDziewu' AS Station_Code, `KpToruDziewu` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbLubObywate' AS Station_Code, `LbLubObywate` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzCzerni' AS Station_Code, `LdLodzCzerni` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzGdansk' AS Station_Code, `LdLodzGdansk` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdZgieMielcz' AS Station_Code, `LdZgieMielcz` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuZielKrotka' AS Station_Code, `LuZielKrotka` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakAlKras' AS Station_Code, `MpKrakAlKras` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakBujaka' AS Station_Code, `MpKrakBujaka` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakBulwar' AS Station_Code, `MpKrakBulwar` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzLegZegrzyn' AS Station_Code, `MzLegZegrzyn` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzPiasPulask' AS Station_Code, `MzPiasPulask` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzPlocMiReja' AS Station_Code, `MzPlocMiReja` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzRadTochter' AS Station_Code, `MzRadTochter` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzSiedKonars' AS Station_Code, `MzSiedKonars` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarAlNiepo' AS Station_Code, `MzWarAlNiepo` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarKondrat' AS Station_Code, `MzWarKondrat` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarMarszal' AS Station_Code, `MzWarMarszal` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarWokalna' AS Station_Code, `MzWarWokalna` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzZyraRoosev' AS Station_Code, `MzZyraRoosev` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'OpKKozBSmial' AS Station_Code, `OpKKozBSmial` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdBialWaszyn' AS Station_Code, `PdBialWaszyn` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdHajnowkJagMOB' AS Station_Code, `PdHajnowkJagMOB` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdSuwPulaski' AS Station_Code, `PdSuwPulaski` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkMielSolski' AS Station_Code, `PkMielSolski` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkPrzemGrunw' AS Station_Code, `PkPrzemGrunw` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PmGdaLeczk08' AS Station_Code, `PmGdaLeczk08` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PmKosTargo12' AS Station_Code, `PmKosTargo12` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkKielJagiel' AS Station_Code, `SkKielJagiel` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkMalo11List' AS Station_Code, `SkMalo11List` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkPolaRuszcz' AS Station_Code, `SkPolaRuszcz` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlGliwicMewy' AS Station_Code, `SlGliwicMewy` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlKatoKossut' AS Station_Code, `SlKatoKossut` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZlotPotLes' AS Station_Code, `SlZlotPotLes` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmOlsPuszkin' AS Station_Code, `WmOlsPuszkin` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpKaliSawick' AS Station_Code, `WpKaliSawick` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpPoznPolank' AS Station_Code, `WpPoznPolank` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczAndr01' AS Station_Code, `ZpSzczAndr01` AS Pollution_Level FROM `2016_pm2.5_1g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczPils02' AS Station_Code, `ZpSzczPils02` AS Pollution_Level FROM `2016_pm2.5_1g`;