DROP TABLE PM25_24g_cons;

CREATE TABLE PM25_24g_cons
SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBulw6118' AS Station_Code, `MpKrakowWIOSBulw6118` AS Pollution_Level FROM `2002_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSPrad6115' AS Station_Code, `MpKrakowWIOSPrad6115` AS Pollution_Level FROM `2002_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSPrad6115' AS Station_Code, `MpKrakowWIOSPrad6115` AS Pollution_Level FROM `2003_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzWSSEMLegiono' AS Station_Code, `LdLodzWSSEMLegiono` AS Pollution_Level FROM `2004_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzWSSEMLegiono' AS Station_Code, `LdLodzWSSEMLegiono` AS Pollution_Level FROM `2005_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlCzestCzes_rzasa' AS Station_Code, `SlCzestCzes_rzasa` AS Pollution_Level FROM `2005_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzWSSEMLegiono' AS Station_Code, `LdLodzWSSEMLegiono` AS Pollution_Level FROM `2006_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.63.wDSMm' AS Station_Code, `Pm.63.wDSMm` AS Pollution_Level FROM `2006_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZabrzZabr_sklod' AS Station_Code, `SlZabrzZabr_sklod` AS Pollution_Level FROM `2006_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbLublinPiel' AS Station_Code, `LbLublinPiel` AS Pollution_Level FROM `2007_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzWSSEMLegiono' AS Station_Code, `LdLodzWSSEMLegiono` AS Pollution_Level FROM `2007_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBulw6118' AS Station_Code, `MpKrakowWIOSBulw6118` AS Pollution_Level FROM `2007_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarszSGGW' AS Station_Code, `MzWarszSGGW` AS Pollution_Level FROM `2007_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZabrzZabr_sklod' AS Station_Code, `SlZabrzZabr_sklod` AS Pollution_Level FROM `2007_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWrocKorzA' AS Station_Code, `DsWrocKorzA` AS Pollution_Level FROM `2008_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbLublinPiel' AS Station_Code, `LbLublinPiel` AS Pollution_Level FROM `2008_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzWSSEMLegiono' AS Station_Code, `LdLodzWSSEMLegiono` AS Pollution_Level FROM `2008_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBulw6118' AS Station_Code, `MpKrakowWIOSBulw6118` AS Pollution_Level FROM `2008_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSPrad6115' AS Station_Code, `MpKrakowWIOSPrad6115` AS Pollution_Level FROM `2008_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.63.wDSMm' AS Station_Code, `Pm.63.wDSMm` AS Pollution_Level FROM `2008_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlKatowKato_kossu' AS Station_Code, `SlKatowKato_kossu` AS Pollution_Level FROM `2008_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZabrzZabr_sklod' AS Station_Code, `SlZabrzZabr_sklod` AS Pollution_Level FROM `2008_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZoryzZory_sikor' AS Station_Code, `SlZoryzZory_sikor` AS Pollution_Level FROM `2008_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWrocKorzA' AS Station_Code, `DsWrocKorzA` AS Pollution_Level FROM `2009_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbLublinPiel' AS Station_Code, `LbLublinPiel` AS Pollution_Level FROM `2009_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzWSSEMLegiono' AS Station_Code, `LdLodzWSSEMLegiono` AS Pollution_Level FROM `2009_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBulw6118' AS Station_Code, `MpKrakowWIOSBulw6118` AS Pollution_Level FROM `2009_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSPrad6115' AS Station_Code, `MpKrakowWIOSPrad6115` AS Pollution_Level FROM `2009_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpTarnowWIOSSoli6303' AS Station_Code, `MpTarnowWIOSSoli6303` AS Pollution_Level FROM `2009_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzPlockReja' AS Station_Code, `MzPlockReja` AS Pollution_Level FROM `2009_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzRadomTochter' AS Station_Code, `MzRadomTochter` AS Pollution_Level FROM `2009_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarszUrsynow' AS Station_Code, `MzWarszUrsynow` AS Pollution_Level FROM `2009_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.63.wDSMm' AS Station_Code, `Pm.63.wDSMm` AS Pollution_Level FROM `2009_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlKatowKato_kossu' AS Station_Code, `SlKatowKato_kossu` AS Pollution_Level FROM `2009_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZabrzZabr_sklod' AS Station_Code, `SlZabrzZabr_sklod` AS Pollution_Level FROM `2009_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZoryzZory_sikor' AS Station_Code, `SlZoryzZory_sikor` AS Pollution_Level FROM `2009_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmPuszcz_IOS_Borecka' AS Station_Code, `WmPuszcz_IOS_Borecka` AS Pollution_Level FROM `2009_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsLegRzeczA' AS Station_Code, `DsLegRzeczA` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsOsieczow' AS Station_Code, `DsOsieczow` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWalbWysA' AS Station_Code, `DsWalbWysA` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWrocGrobla' AS Station_Code, `DsWrocGrobla` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWrocKorzA' AS Station_Code, `DsWrocKorzA` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpBydgBerlinga' AS Station_Code, `KpBydgBerlinga` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpTorunDziewulsk' AS Station_Code, `KpTorunDziewulsk` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpWloclSielska' AS Station_Code, `KpWloclSielska` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpZielBoryTuch' AS Station_Code, `KpZielBoryTuch` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbBialaPOrzechowa' AS Station_Code, `LbBialaPOrzechowa` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbChelmJagWIOS' AS Station_Code, `LbChelmJagWIOS` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbLublin_Sliwins_5' AS Station_Code, `LbLublin_Sliwins_5` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbZamoscHrubieszowsk' AS Station_Code, `LbZamoscHrubieszowsk` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzWIOSACzernik' AS Station_Code, `LdLodzWIOSACzernik` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzWSSEMLegiono' AS Station_Code, `LdLodzWSSEMLegiono` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdPiotrkWIOSMSienkie' AS Station_Code, `LdPiotrkWIOSMSienkie` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuGorzowWIOS_MAN' AS Station_Code, `LuGorzowWIOS_MAN` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuWschowWIOS_AUT' AS Station_Code, `LuWschowWIOS_AUT` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuZgoraWIOS_AUT' AS Station_Code, `LuZgoraWIOS_AUT` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBuja6119' AS Station_Code, `MpKrakowWIOSBuja6119` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBulw6118' AS Station_Code, `MpKrakowWIOSBulw6118` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpNSaczWIOSPija6204' AS Station_Code, `MpNSaczWIOSPija6204` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpTarnowWIOSBitw6304' AS Station_Code, `MpTarnowWIOSBitw6304` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpTrzebiWIOSZWM0305' AS Station_Code, `MpTrzebiWIOSZWM0305` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpZakopaWIOSRown1701' AS Station_Code, `MpZakopaWIOSRown1701` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzPiastowPulask' AS Station_Code, `MzPiastowPulask` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzPlockReja' AS Station_Code, `MzPlockReja` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzRadomHallera' AS Station_Code, `MzRadomHallera` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzRadomTochter' AS Station_Code, `MzRadomTochter` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarszUrsynow' AS Station_Code, `MzWarszUrsynow` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarTarKondra' AS Station_Code, `MzWarTarKondra` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'OpKlucz2pyl' AS Station_Code, `OpKlucz2pyl` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'OpOpole4pyl' AS Station_Code, `OpOpole4pyl` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdBialyWarszawska' AS Station_Code, `PdBialyWarszawska` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdLomzaSikorskiego' AS Station_Code, `PdLomzaSikorskiego` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkKrosnoWIOSKletowki' AS Station_Code, `PkKrosnoWIOSKletowki` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkNiskoWIOSSzklar' AS Station_Code, `PkNiskoWIOSSzklar` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkRzeszWIOSNoweMiasto' AS Station_Code, `PkRzeszWIOSNoweMiasto` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkRzeszWIOSSzop' AS Station_Code, `PkRzeszWIOSSzop` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.01w.02m' AS Station_Code, `Pm.01w.02m` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.63.wDSAa' AS Station_Code, `Pm.63.wDSAa` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.63.wDSMm' AS Station_Code, `Pm.63.wDSMm` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.aw07m' AS Station_Code, `Pm.aw07m` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.aw08m' AS Station_Code, `Pm.aw08m` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkBuskoWios2' AS Station_Code, `SkBuskoWios2` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkKielJagielWios' AS Station_Code, `SkKielJagielWios` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlBielbBiel_stern' AS Station_Code, `SlBielbBiel_stern` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlCzestCzes_zana6' AS Station_Code, `SlCzestCzes_zana6` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlGliwiGliw_mewy' AS Station_Code, `SlGliwiGliw_mewy` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlGodowWodz_wodzi' AS Station_Code, `SlGodowWodz_wodzi` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlKatowKato_kossu' AS Station_Code, `SlKatowKato_kossu` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZlotyJano_lesni' AS Station_Code, `SlZlotyJano_lesni` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZoryzZory_sikor' AS Station_Code, `SlZoryzZory_sikor` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmElblagWIOS_Bazynsk' AS Station_Code, `WmElblagWIOS_Bazynsk` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmOlsztyWIOS_Puszkin' AS Station_Code, `WmOlsztyWIOS_Puszkin` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmOstrodWIOS_Chrobre' AS Station_Code, `WmOstrodWIOS_Chrobre` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmPuszcz_IOS_Borecka' AS Station_Code, `WmPuszcz_IOS_Borecka` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpKoszalin006' AS Station_Code, `ZpKoszalin006` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpMysMysliborz007' AS Station_Code, `ZpMysMysliborz007` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzcSzczecinek008' AS Station_Code, `ZpSzcSzczecinek008` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczecin001' AS Station_Code, `ZpSzczecin001` AS Pollution_Level FROM `2010_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsLegRzeczA' AS Station_Code, `DsLegRzeczA` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsOsieczow' AS Station_Code, `DsOsieczow` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWalbWysA' AS Station_Code, `DsWalbWysA` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWrocGrobla' AS Station_Code, `DsWrocGrobla` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWrocWisA' AS Station_Code, `DsWrocWisA` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpBydgBerlinga' AS Station_Code, `KpBydgBerlinga` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpGrudzStar' AS Station_Code, `KpGrudzStar` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpTorunDziewulsk' AS Station_Code, `KpTorunDziewulsk` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpWloclSielska' AS Station_Code, `KpWloclSielska` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpZielBoryTuch' AS Station_Code, `KpZielBoryTuch` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbBialaPOrzechowa' AS Station_Code, `LbBialaPOrzechowa` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbChelmJagWIOS' AS Station_Code, `LbChelmJagWIOS` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbLublin_Sliwins_5' AS Station_Code, `LbLublin_Sliwins_5` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbZamoscHrubieszowsk' AS Station_Code, `LbZamoscHrubieszowsk` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzWIOSACzernik' AS Station_Code, `LdLodzWIOSACzernik` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzWSSEMLegiono' AS Station_Code, `LdLodzWSSEMLegiono` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdPiotrkWIOSMSienkie' AS Station_Code, `LdPiotrkWIOSMSienkie` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuGorzowWIOS_MAN' AS Station_Code, `LuGorzowWIOS_MAN` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuWschowWIOS_AUT' AS Station_Code, `LuWschowWIOS_AUT` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuZgoraWIOS_AUT' AS Station_Code, `LuZgoraWIOS_AUT` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpBochniWIOSKBar0106' AS Station_Code, `MpBochniWIOSKBar0106` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSAKra6117' AS Station_Code, `MpKrakowWIOSAKra6117` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBuja6119' AS Station_Code, `MpKrakowWIOSBuja6119` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBulw6118' AS Station_Code, `MpKrakowWIOSBulw6118` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpNSaczWIOSNadb6205' AS Station_Code, `MpNSaczWIOSNadb6205` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpTarnowWIOSBitw6304' AS Station_Code, `MpTarnowWIOSBitw6304` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpTrzebiWIOSZWM0305' AS Station_Code, `MpTrzebiWIOSZWM0305` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpZakopaWIOSRown1701' AS Station_Code, `MpZakopaWIOSRown1701` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzPiastowPulask' AS Station_Code, `MzPiastowPulask` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzPlockReja' AS Station_Code, `MzPlockReja` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzRadomHallera' AS Station_Code, `MzRadomHallera` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarNiepodKom' AS Station_Code, `MzWarNiepodKom` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarszUrsynow' AS Station_Code, `MzWarszUrsynow` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarTarKondra' AS Station_Code, `MzWarTarKondra` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'OpKlucz2pyl' AS Station_Code, `OpKlucz2pyl` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'OpOpole4pyl' AS Station_Code, `OpOpole4pyl` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdBialyWarszawska' AS Station_Code, `PdBialyWarszawska` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdLomzaSikorskiego' AS Station_Code, `PdLomzaSikorskiego` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkKrosnoWIOSKletowki' AS Station_Code, `PkKrosnoWIOSKletowki` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkNiskoWIOSSzklar' AS Station_Code, `PkNiskoWIOSSzklar` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkRzeszWIOSNoweMiasto' AS Station_Code, `PkRzeszWIOSNoweMiasto` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkRzeszWIOSSzop' AS Station_Code, `PkRzeszWIOSSzop` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.01w.02m' AS Station_Code, `Pm.01w.02m` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.63.wDSAa' AS Station_Code, `Pm.63.wDSAa` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.63.wDSMm' AS Station_Code, `Pm.63.wDSMm` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.aw08m' AS Station_Code, `Pm.aw08m` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkBuskoWios2' AS Station_Code, `SkBuskoWios2` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkKielJagielWios' AS Station_Code, `SkKielJagielWios` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlBielbBiel_stern' AS Station_Code, `SlBielbBiel_stern` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlCzestCzes_zana6' AS Station_Code, `SlCzestCzes_zana6` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlGliwiGliw_mewy' AS Station_Code, `SlGliwiGliw_mewy` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlGodowWodz_wodzi' AS Station_Code, `SlGodowWodz_wodzi` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlKatowKato_aleja' AS Station_Code, `SlKatowKato_aleja` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlKatowKato_kossu' AS Station_Code, `SlKatowKato_kossu` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZlotyJano_lesni' AS Station_Code, `SlZlotyJano_lesni` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZoryzZory_sikor' AS Station_Code, `SlZoryzZory_sikor` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmElblagWIOS_Bazynsk' AS Station_Code, `WmElblagWIOS_Bazynsk` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmOlsztyWIOS_Puszkin' AS Station_Code, `WmOlsztyWIOS_Puszkin` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmOstrodWIOS_Chrobre' AS Station_Code, `WmOstrodWIOS_Chrobre` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmPuszcz_IOS_Borecka' AS Station_Code, `WmPuszcz_IOS_Borecka` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpWKP001' AS Station_Code, `WpWKP001` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpWKPKalisz007/10' AS Station_Code, `WpWKPKalisz007/10` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpKoszalin006' AS Station_Code, `ZpKoszalin006` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpMysMysliborz007' AS Station_Code, `ZpMysMysliborz007` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzcSzczecinek008' AS Station_Code, `ZpSzcSzczecinek008` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczecin001' AS Station_Code, `ZpSzczecin001` AS Pollution_Level FROM `2011_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsLegRzeczA' AS Station_Code, `DsLegRzeczA` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsOsieczow' AS Station_Code, `DsOsieczow` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWalbWysA' AS Station_Code, `DsWalbWysA` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWrocGrobla' AS Station_Code, `DsWrocGrobla` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWrocWisA' AS Station_Code, `DsWrocWisA` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpBydgBerlinga' AS Station_Code, `KpBydgBerlinga` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpTorunDziewulsk' AS Station_Code, `KpTorunDziewulsk` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpWloclSielska' AS Station_Code, `KpWloclSielska` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpZielBoryTuch' AS Station_Code, `KpZielBoryTuch` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbBialaPOrzechowa' AS Station_Code, `LbBialaPOrzechowa` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbChelmJagWIOS' AS Station_Code, `LbChelmJagWIOS` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbLublin_Sliwins_5' AS Station_Code, `LbLublin_Sliwins_5` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbZamoscHrubieszowsk' AS Station_Code, `LbZamoscHrubieszowsk` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzWIOSACzernik' AS Station_Code, `LdLodzWIOSACzernik` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdPiotrkWIOSMSienkie' AS Station_Code, `LdPiotrkWIOSMSienkie` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuGorzowWIOS_MAN' AS Station_Code, `LuGorzowWIOS_MAN` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuWschowWIOS_AUT' AS Station_Code, `LuWschowWIOS_AUT` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuZgoraWIOS_AUT' AS Station_Code, `LuZgoraWIOS_AUT` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpBochniWIOSKBar0106' AS Station_Code, `MpBochniWIOSKBar0106` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSAKra6117' AS Station_Code, `MpKrakowWIOSAKra6117` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBuja6119' AS Station_Code, `MpKrakowWIOSBuja6119` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBulw6118' AS Station_Code, `MpKrakowWIOSBulw6118` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpNSaczWIOSNadb6205' AS Station_Code, `MpNSaczWIOSNadb6205` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpTarnowWIOSBitw6304' AS Station_Code, `MpTarnowWIOSBitw6304` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpTrzebiWIOSZWM0305' AS Station_Code, `MpTrzebiWIOSZWM0305` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpZakopaWIOSRown1701' AS Station_Code, `MpZakopaWIOSRown1701` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzPiastowPulask' AS Station_Code, `MzPiastowPulask` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzPlockReja' AS Station_Code, `MzPlockReja` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzRadomHallera' AS Station_Code, `MzRadomHallera` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarszUrsynow' AS Station_Code, `MzWarszUrsynow` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarTarKondra' AS Station_Code, `MzWarTarKondra` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'OpKlucz2pyl' AS Station_Code, `OpKlucz2pyl` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'OpOpole4pyl' AS Station_Code, `OpOpole4pyl` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdBialyWarszawska' AS Station_Code, `PdBialyWarszawska` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdLomzaSikorskiego' AS Station_Code, `PdLomzaSikorskiego` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkKrosnoWIOSKletowki' AS Station_Code, `PkKrosnoWIOSKletowki` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkNiskoWIOSSzklar' AS Station_Code, `PkNiskoWIOSSzklar` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkRzeszWIOSNoweMiasto' AS Station_Code, `PkRzeszWIOSNoweMiasto` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkRzeszWIOSSzop' AS Station_Code, `PkRzeszWIOSSzop` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.01w.02m' AS Station_Code, `Pm.01w.02m` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.63.wDSAa' AS Station_Code, `Pm.63.wDSAa` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.63.wDSMm' AS Station_Code, `Pm.63.wDSMm` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.AM12.a' AS Station_Code, `Pm.AM12.a` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkBuskoWios2' AS Station_Code, `SkBuskoWios2` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkKielJagielWios' AS Station_Code, `SkKielJagielWios` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkStaracZlota2' AS Station_Code, `SkStaracZlota2` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlBielbBiel_stern' AS Station_Code, `SlBielbBiel_stern` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlCzestCzes_zana6' AS Station_Code, `SlCzestCzes_zana6` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlGliwiGliw_mewy' AS Station_Code, `SlGliwiGliw_mewy` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlGodowWodz_wodzi' AS Station_Code, `SlGodowWodz_wodzi` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlKatowKato_aleja' AS Station_Code, `SlKatowKato_aleja` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlKatowKato_kossu' AS Station_Code, `SlKatowKato_kossu` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZlotyJano_lesni' AS Station_Code, `SlZlotyJano_lesni` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZoryzZory_sikor' AS Station_Code, `SlZoryzZory_sikor` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmElblagWIOS_Bazynsk' AS Station_Code, `WmElblagWIOS_Bazynsk` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmOlsztyWIOS_Puszkin' AS Station_Code, `WmOlsztyWIOS_Puszkin` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmOstrodWIOS_Chrobre' AS Station_Code, `WmOstrodWIOS_Chrobre` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmPuszcz_IOS_Borecka' AS Station_Code, `WmPuszcz_IOS_Borecka` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpWKP001' AS Station_Code, `WpWKP001` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpKoszalin006' AS Station_Code, `ZpKoszalin006` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpMysMysliborz007' AS Station_Code, `ZpMysMysliborz007` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzcSzczecinek008' AS Station_Code, `ZpSzcSzczecinek008` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczecin001' AS Station_Code, `ZpSzczecin001` AS Pollution_Level FROM `2012_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsLegRzeczA' AS Station_Code, `DsLegRzeczA` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsOsieczow' AS Station_Code, `DsOsieczow` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWalbWysA' AS Station_Code, `DsWalbWysA` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWrocGrobla' AS Station_Code, `DsWrocGrobla` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsZgorzBohA' AS Station_Code, `DsZgorzBohA` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpBydgBerlinga' AS Station_Code, `KpBydgBerlinga` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpGrudzStar' AS Station_Code, `KpGrudzStar` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpTorunDziewulsk' AS Station_Code, `KpTorunDziewulsk` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpWloclSielska' AS Station_Code, `KpWloclSielska` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpZielBoryTuch' AS Station_Code, `KpZielBoryTuch` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbBialaPOrzechowa' AS Station_Code, `LbBialaPOrzechowa` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbChelmJagWIOS' AS Station_Code, `LbChelmJagWIOS` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbLublin_Sliwins_5' AS Station_Code, `LbLublin_Sliwins_5` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbZamoscHrubieszowsk' AS Station_Code, `LbZamoscHrubieszowsk` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzWIOSACzernik' AS Station_Code, `LdLodzWIOSACzernik` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzWSSEMLegiono' AS Station_Code, `LdLodzWSSEMLegiono` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdPiotrkWIOSMSienkie' AS Station_Code, `LdPiotrkWIOSMSienkie` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuGorzowWIOS_MAN' AS Station_Code, `LuGorzowWIOS_MAN` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuWschowWIOS_AUT' AS Station_Code, `LuWschowWIOS_AUT` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuZgoraWIOS_AUT' AS Station_Code, `LuZgoraWIOS_AUT` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpBochniWIOSKBar0106' AS Station_Code, `MpBochniWIOSKBar0106` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBuja6119' AS Station_Code, `MpKrakowWIOSBuja6119` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpNSaczWIOSNadb6205' AS Station_Code, `MpNSaczWIOSNadb6205` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpTarnowWIOSBitw6304' AS Station_Code, `MpTarnowWIOSBitw6304` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpTrzebiWIOSZWM0305' AS Station_Code, `MpTrzebiWIOSZWM0305` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpZakopaWIOSRown1701' AS Station_Code, `MpZakopaWIOSRown1701` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzPiastowPulask' AS Station_Code, `MzPiastowPulask` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzPlockPKN' AS Station_Code, `MzPlockPKN` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzRadomHallera' AS Station_Code, `MzRadomHallera` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarszUrsynow' AS Station_Code, `MzWarszUrsynow` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarTarKondra' AS Station_Code, `MzWarTarKondra` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'OpKlucz2pyl' AS Station_Code, `OpKlucz2pyl` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'OpOpole4pyl' AS Station_Code, `OpOpole4pyl` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdBialyWarszawska' AS Station_Code, `PdBialyWarszawska` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdLomzaSikorskiego' AS Station_Code, `PdLomzaSikorskiego` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkKrosnoWIOSKletowki' AS Station_Code, `PkKrosnoWIOSKletowki` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkNiskoWIOSSzklar' AS Station_Code, `PkNiskoWIOSSzklar` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkRzeszWIOSNoweMiasto' AS Station_Code, `PkRzeszWIOSNoweMiasto` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.01w.02m' AS Station_Code, `Pm.01w.02m` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.AM12.a' AS Station_Code, `Pm.AM12.a` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkBuskoWios2' AS Station_Code, `SkBuskoWios2` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkKielJagielWios' AS Station_Code, `SkKielJagielWios` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkStaracZlota2' AS Station_Code, `SkStaracZlota2` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlBielbBiel_stern' AS Station_Code, `SlBielbBiel_stern` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlCzestCzes_zana6' AS Station_Code, `SlCzestCzes_zana6` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlGliwiGliw_mewy' AS Station_Code, `SlGliwiGliw_mewy` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlGodowWodz_wodzi' AS Station_Code, `SlGodowWodz_wodzi` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlKatowKato_aleja' AS Station_Code, `SlKatowKato_aleja` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlKatowKato_kossu' AS Station_Code, `SlKatowKato_kossu` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZlotyJano_lesni' AS Station_Code, `SlZlotyJano_lesni` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZoryzZory_sikor' AS Station_Code, `SlZoryzZory_sikor` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmElblagWIOS_Bazynsk' AS Station_Code, `WmElblagWIOS_Bazynsk` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmOlsztyWIOS_Puszkin' AS Station_Code, `WmOlsztyWIOS_Puszkin` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmOstrodWIOS_Chrobre' AS Station_Code, `WmOstrodWIOS_Chrobre` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmPuszcz_IOS_Borecka' AS Station_Code, `WmPuszcz_IOS_Borecka` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpWKP001' AS Station_Code, `WpWKP001` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpWKPKalisz007/10' AS Station_Code, `WpWKPKalisz007/10` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpKoszalin006' AS Station_Code, `ZpKoszalin006` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpMysMysliborz007' AS Station_Code, `ZpMysMysliborz007` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzcSzczecinek008' AS Station_Code, `ZpSzcSzczecinek008` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczecin001' AS Station_Code, `ZpSzczecin001` AS Pollution_Level FROM `2013_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsLegRzeczA' AS Station_Code, `DsLegRzeczA` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsOsieczow' AS Station_Code, `DsOsieczow` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWalbWysA' AS Station_Code, `DsWalbWysA` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWrocGrobla' AS Station_Code, `DsWrocGrobla` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsZgorzBohA' AS Station_Code, `DsZgorzBohA` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpBydgBerlinga' AS Station_Code, `KpBydgBerlinga` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpGrudzStar' AS Station_Code, `KpGrudzStar` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpTorunDziewulsk' AS Station_Code, `KpTorunDziewulsk` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpWloclSielska' AS Station_Code, `KpWloclSielska` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpZielBoryTuch' AS Station_Code, `KpZielBoryTuch` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbBialaPOrzechowa' AS Station_Code, `LbBialaPOrzechowa` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbChelmJagWIOS' AS Station_Code, `LbChelmJagWIOS` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbLublin_Sliwins_5' AS Station_Code, `LbLublin_Sliwins_5` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbZamoscHrubieszowsk' AS Station_Code, `LbZamoscHrubieszowsk` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzWIOSACzernik' AS Station_Code, `LdLodzWIOSACzernik` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzWSSEMLegiono' AS Station_Code, `LdLodzWSSEMLegiono` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdPiotrkWIOSMSienkie' AS Station_Code, `LdPiotrkWIOSMSienkie` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuGorzowWIOS_MAN' AS Station_Code, `LuGorzowWIOS_MAN` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuWschowWIOS_AUT' AS Station_Code, `LuWschowWIOS_AUT` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuZgoraWIOS_AUT' AS Station_Code, `LuZgoraWIOS_AUT` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpBochniWIOSKBar0106' AS Station_Code, `MpBochniWIOSKBar0106` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakowWIOSBuja6119' AS Station_Code, `MpKrakowWIOSBuja6119` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpNSaczWIOSNadb6205' AS Station_Code, `MpNSaczWIOSNadb6205` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpTarnowWIOSBitw6304' AS Station_Code, `MpTarnowWIOSBitw6304` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpTrzebiWIOSZWM0305' AS Station_Code, `MpTrzebiWIOSZWM0305` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpZakopaWIOSRown1701' AS Station_Code, `MpZakopaWIOSRown1701` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzPiastowPulask' AS Station_Code, `MzPiastowPulask` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzPlockPKN' AS Station_Code, `MzPlockPKN` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzRadomHallera' AS Station_Code, `MzRadomHallera` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarszUrsynow' AS Station_Code, `MzWarszUrsynow` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarTarKondra' AS Station_Code, `MzWarTarKondra` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'OpKlucz2pyl' AS Station_Code, `OpKlucz2pyl` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'OpOpole4pyl' AS Station_Code, `OpOpole4pyl` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdBialyWarszawska' AS Station_Code, `PdBialyWarszawska` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdLomzaSikorskiego' AS Station_Code, `PdLomzaSikorskiego` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkJasloWIOSSikorskiego' AS Station_Code, `PkJasloWIOSSikorskiego` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkKrosnoWIOSKletowki' AS Station_Code, `PkKrosnoWIOSKletowki` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkNiskoWIOSSzklar' AS Station_Code, `PkNiskoWIOSSzklar` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkRzeszWIOSNoweMiasto' AS Station_Code, `PkRzeszWIOSNoweMiasto` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.01w.02m' AS Station_Code, `Pm.01w.02m` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.63.wDSAa' AS Station_Code, `Pm.63.wDSAa` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'Pm.AM12.a' AS Station_Code, `Pm.AM12.a` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkBuskoWios2' AS Station_Code, `SkBuskoWios2` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkKielJagielWios' AS Station_Code, `SkKielJagielWios` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkStaracZlota2' AS Station_Code, `SkStaracZlota2` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlBielbBiel_stern' AS Station_Code, `SlBielbBiel_stern` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlCzestCzes_zana6' AS Station_Code, `SlCzestCzes_zana6` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlGliwiGliw_mewy' AS Station_Code, `SlGliwiGliw_mewy` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlGodowWodz_wodzi' AS Station_Code, `SlGodowWodz_wodzi` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlKatowKato_aleja' AS Station_Code, `SlKatowKato_aleja` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlKatowKato_kossu' AS Station_Code, `SlKatowKato_kossu` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlTarnoTarn_litew' AS Station_Code, `SlTarnoTarn_litew` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZlotyJano_lesni' AS Station_Code, `SlZlotyJano_lesni` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZoryzZory_sikor' AS Station_Code, `SlZoryzZory_sikor` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmElblagWIOS_Bazynsk' AS Station_Code, `WmElblagWIOS_Bazynsk` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmOlsztyWIOS_Puszkin' AS Station_Code, `WmOlsztyWIOS_Puszkin` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmOstrodWIOS_Chrobre' AS Station_Code, `WmOstrodWIOS_Chrobre` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmPuszcz_IOS_Borecka' AS Station_Code, `WmPuszcz_IOS_Borecka` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpWKP001' AS Station_Code, `WpWKP001` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpWKPKalisz007/10' AS Station_Code, `WpWKPKalisz007/10` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpKoszalin006' AS Station_Code, `ZpKoszalin006` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpMysMysliborz007' AS Station_Code, `ZpMysMysliborz007` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzcSzczecinek008' AS Station_Code, `ZpSzcSzczecinek008` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczecin001' AS Station_Code, `ZpSzczecin001` AS Pollution_Level FROM `2014_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsLegAlRzecz' AS Station_Code, `DsLegAlRzecz` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsOsieczow21' AS Station_Code, `DsOsieczow21` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWalbrzWyso' AS Station_Code, `DsWalbrzWyso` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsWrocNaGrob' AS Station_Code, `DsWrocNaGrob` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'DsZgorBohGet' AS Station_Code, `DsZgorBohGet` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpBydBerling' AS Station_Code, `KpBydBerling` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpGrudSienki' AS Station_Code, `KpGrudSienki` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpToruDziewu' AS Station_Code, `KpToruDziewu` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpWloclSiels' AS Station_Code, `KpWloclSiels` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'KpZielBoryTu' AS Station_Code, `KpZielBoryTu` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbBiaPodOrze' AS Station_Code, `LbBiaPodOrze` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbChelJagiel' AS Station_Code, `LbChelJagiel` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbLubSliwins' AS Station_Code, `LbLubSliwins` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LbZamoHrubie' AS Station_Code, `LbZamoHrubie` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzCzerni' AS Station_Code, `LdLodzCzerni` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdLodzLegion' AS Station_Code, `LdLodzLegion` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LdPioTrKraPr' AS Station_Code, `LdPioTrKraPr` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuGorzPilsud' AS Station_Code, `LuGorzPilsud` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuZarySzyman' AS Station_Code, `LuZarySzyman` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'LuZielKrotka' AS Station_Code, `LuZielKrotka` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpBochKonfed' AS Station_Code, `MpBochKonfed` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpKrakBujaka' AS Station_Code, `MpKrakBujaka` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpNoSaczNadb' AS Station_Code, `MpNoSaczNadb` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpTarBitStud' AS Station_Code, `MpTarBitStud` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpTrzebOsZWM' AS Station_Code, `MpTrzebOsZWM` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MpZakopaSien' AS Station_Code, `MpZakopaSien` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzPlocKroJad' AS Station_Code, `MzPlocKroJad` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzRadHallera' AS Station_Code, `MzRadHallera` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarKondrat' AS Station_Code, `MzWarKondrat` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'MzWarWokalna' AS Station_Code, `MzWarWokalna` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'OpKluczMicki' AS Station_Code, `OpKluczMicki` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'OpOpoleOsAKr' AS Station_Code, `OpOpoleOsAKr` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdBialWarsza' AS Station_Code, `PdBialWarsza` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PdLomSikorsk' AS Station_Code, `PdLomSikorsk` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkJasloSikor' AS Station_Code, `PkJasloSikor` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkKrosKletow' AS Station_Code, `PkKrosKletow` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkNiskoSzkla' AS Station_Code, `PkNiskoSzkla` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PkRzeszRejta' AS Station_Code, `PkRzeszRejta` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PmGdaPowWiel' AS Station_Code, `PmGdaPowWiel` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PmKosTargo12' AS Station_Code, `PmKosTargo12` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'PmSlupKniazi' AS Station_Code, `PmSlupKniazi` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkBuskRokosz' AS Station_Code, `SkBuskRokosz` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkKielJagiel' AS Station_Code, `SkKielJagiel` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkKielWarsza' AS Station_Code, `SkKielWarsza` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SkStaraZlota' AS Station_Code, `SkStaraZlota` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlBielSterni' AS Station_Code, `SlBielSterni` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlCzestoZana' AS Station_Code, `SlCzestoZana` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlGliwicMewy' AS Station_Code, `SlGliwicMewy` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlGodGliniki' AS Station_Code, `SlGodGliniki` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlKatoKossut' AS Station_Code, `SlKatoKossut` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlKatoPlebA4' AS Station_Code, `SlKatoPlebA4` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlTarnoLitew' AS Station_Code, `SlTarnoLitew` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZlotPotLes' AS Station_Code, `SlZlotPotLes` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'SlZorySikors' AS Station_Code, `SlZorySikors` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmElbBazynsk' AS Station_Code, `WmElbBazynsk` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmOlsPuszkin' AS Station_Code, `WmOlsPuszkin` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmOstrChrobr' AS Station_Code, `WmOstrChrobr` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WmPuszczaBor' AS Station_Code, `WmPuszczaBor` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpKaliSawick' AS Station_Code, `WpKaliSawick` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpPleszAlMic' AS Station_Code, `WpPleszAlMic` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'WpPoznPolank' AS Station_Code, `WpPoznPolank` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpKoszSpasow' AS Station_Code, `ZpKoszSpasow` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpMyslZaBram' AS Station_Code, `ZpMyslZaBram` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczAndr01' AS Station_Code, `ZpSzczAndr01` AS Pollution_Level FROM `2016_pm2.5_24g`
UNION ALL SELECT `Kod stacji` AS Measure_Date, 'ZpSzczec1Maj' AS Station_Code, `ZpSzczec1Maj` AS Pollution_Level FROM `2016_pm2.5_24g`;